name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify toolchain
        run: |
          echo "Node: $(node -v)"
          echo "pnpm: $(pnpm -v)"
          test -f pnpm-lock.yaml

      - name: Assert pnpm version matches packageManager
        run: |
          EXPECT=$(node -p "require('./package.json').packageManager.split('@')[1]")
          ACTUAL=$(pnpm -v)
          echo "expect pnpm $EXPECT, actual $ACTUAL"
          [ "$ACTUAL" = "$EXPECT" ]

      - name: Install (frozen)
        run: pnpm install --frozen-lockfile

      - name: Build Dieter and copy assets
        run: |
          pnpm --filter @ck/dieter build
          pnpm run build:assets

      - name: Build packages
        run: |
          pnpm --filter @ck/studio-shell build
          pnpm --filter @ck/app build

      - name: CI enforcement checks
        run: |
          # Fail if any committed files under apps/app/public/dieter
          test -z "$(git ls-files 'apps/app/public/dieter/**')" || (echo "apps/app/public/dieter should not be committed" && exit 1)
          # Verify Dieter dist exists
          test -d dieter/dist || (echo "dieter/dist missing after build" && exit 1)
          # Verify no @ck/dieter/icons imports
          if grep -R -n --include='*.ts' --include='*.tsx' "@ck/dieter/icons" .; then echo "Found forbidden @ck/dieter/icons imports" && exit 1; fi
          # No .zip files
          test -z "$(git ls-files '*.zip')" || (echo "zip files are not allowed in repo" && exit 1)
