name: CI
on:
  push:
    branches: ["**"]
    paths-ignore:
      - "documentation/**"
      - "**/*.md"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "documentation/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use packageManager version
        run: corepack install

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles(pnpm-lock.yaml) }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies (frozen)
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm -r -w run typecheck || true

      - name: Lint
        run: pnpm -r -w run lint || true

      - name: Build
        run: pnpm -r -w run build
