name: Dieter Guardrails
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "documentation/**"
      - "**/*.md"
  push:
    branches: [ "**" ]
    paths-ignore:
      - "documentation/**"
      - "**/*.md"

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Verify Corepack availability
        run: corepack --version || npm install -g corepack

      - name: Use packageManager version
        run: corepack install

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify toolchain
        run: |
          echo "Node: $(node -v)"
          echo "pnpm: $(pnpm -v)"
          test -f pnpm-lock.yaml

      - name: Install (frozen)
        run: pnpm install --frozen-lockfile

      - name: Build Dieter and copy assets
        run: |
          pnpm --filter @ck/dieter build
          pnpm run build:assets

      - name: Fail on legacy Dieter imports
        run: |
          set -e
          # Detect ESM-style imports from legacy path
          if grep -R "from \(['\"]apps/app/dieter" --include="*.ts" --include="*.tsx" .; then
            echo "Legacy Dieter import detected (ESM-style)."; exit 1;
          fi
          # Detect CommonJS requires from legacy path
          if grep -R "require(.*['\"]apps/app/dieter" --include="*.ts" --include="*.tsx" .; then
            echo "Legacy Dieter import detected (CJS-style)."; exit 1;
          fi
          echo "✓ No legacy Dieter imports found."

      - name: Verify Dieter assets directory exists
        run: |
          set -e
          if [ -d apps/app/public/dieter ]; then
            echo "✓ Dieter assets directory exists"
          else
            echo "✗ Missing Dieter assets directory"
            ls -la apps/app/public || true
            exit 1
          fi

      - name: Verify Dieter asset reachable
        run: |
          set -e
          if [ -f apps/app/public/dieter/tokens.css ]; then
            echo "✓ Dieter assets accessible"
          else
            echo "✗ Dieter assets not found at apps/app/public/dieter/tokens.css"
            ls -la apps/app/public/dieter || true
            exit 1
          fi


