name: docs-check
on:
  pull_request:
    paths:
      - "documentation/**"
      - "tools/docs/**"
      - ".github/workflows/docs-check.yml"
  push:
    branches: ["**"]
    paths:
      - "documentation/**"
      - "tools/docs/**"
      - ".github/workflows/docs-check.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use packageManager version
        run: corepack install

      - name: Probe docs tree
        id: probe
        shell: bash
        run: |
          if [ -d documentation ] && [ -d documentation/systems/core ]; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
          else
            echo "No documentation/systems/core present — skipping docs validation."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate services index
        if: steps.probe.outputs.skip != 'true'
        run: pnpm -s node tools/docs/generate-services.mjs

      - name: Ensure SERVICES_INDEX.md is up to date
        if: steps.probe.outputs.skip != 'true'
        shell: bash
        run: |
          if ! git diff --quiet -- documentation/SERVICES_INDEX.md; then
            echo "Generator output is stale. Run: pnpm -s node tools/docs/generate-services.mjs and commit."
            exit 1
          fi
