name: Sync ERD (SchemaCrawler)

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  erd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse SUPABASE_DB_URL
        id: parse
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          if [[ ! "$SUPABASE_DB_URL" =~ ^postgres(ql)?://([^:]+):([^@]+)@([^:/]+)(:([0-9]+))?/(.+)$ ]]; then
            echo "Bad SUPABASE_DB_URL format"
            exit 1
          fi
          echo "user=${BASH_REMATCH[2]}"     >> $GITHUB_OUTPUT
          echo "pass=${BASH_REMATCH[3]}"     >> $GITHUB_OUTPUT
          echo "host=${BASH_REMATCH[4]}"     >> $GITHUB_OUTPUT
          echo "port=${BASH_REMATCH[6]:-5432}" >> $GITHUB_OUTPUT
          echo "db=${BASH_REMATCH[7]}"       >> $GITHUB_OUTPUT

      - name: Ensure output folder
        run: |
          mkdir -p docs/architecture/DBschema

      - name: Generate ERD (PNG) with SchemaCrawler
        env:
          JDBC_URL: jdbc:postgresql://${{ steps.parse.outputs.host }}:${{ steps.parse.outputs.port }}/${{ steps.parse.outputs.db }}
          DB_USER:  ${{ steps.parse.outputs.user }}
          DB_PASS:  ${{ steps.parse.outputs.pass }}
        run: |
          set -euo pipefail
          docker run --rm \
            -v "$PWD/docs/architecture/DBschema:/out" \
            schemacrawler/schemacrawler:latest \
            --server=postgresql \
            --url="$JDBC_URL" \
            --user="$DB_USER" \
            --password="$DB_PASS" \
            --schemas=public \
            --info-level=standard \
            --command=schema \
            --output-format=png \
            --output-file=/out/erd.png

      - name: Commit ERD if changed
        run: |
          set -euo pipefail
          git add docs/architecture/DBschema/erd.png
          if git diff --cached --quiet; then
            echo "No ERD changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(erd): refresh ERD [skip ci]"
          git push
