name: guard-no-oslo
on:
  pull_request:
    paths:
      - '**/*'
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if retired codename appears
        run: |
          ! grep -R --line-number -I '\bOslo\b' . || (echo 'Retired codename Oslo found in content.' && exit 1)
          ! git ls-files | grep -i '/oslo' || (echo 'Retired codename Oslo found in filename/path.' && exit 1)
