name: Document Schema

on:
  schedule:
    - cron: '0 2 * * *'   # Daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tbls (schema doc generator)
        run: |
          curl -Ls https://github.com/k1LoW/tbls/releases/download/v1.70.0/tbls_v1.70.0_linux_amd64.tar.gz \
          | tar xz
          sudo mv tbls /usr/local/bin/

      - name: Generate docs to docs/schema
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          mkdir -p docs/schema
          # tbls will connect read-only and output Markdown files under docs/schema
          tbls doc "$DATABASE_URL" docs/schema --force

      - name: Commit changes (if any)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          git add docs/schema/
          git diff --staged --quiet || git commit -m "docs: update schema [skip ci]"
          git push
