name: Supabase Schema Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2 * * *'   # daily at 02:05 UTC

permissions:
  contents: write

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump public schema (pg_dump over SSL)
        env:
          URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          mkdir -p docs/architecture/DBschema

          # Optional: quick connectivity probe with clear error
          echo "Probing DB connectivity…"
          psql "${URL}?sslmode=require" -Atqc 'select 1' >/dev/null

          # Dump structure only
          pg_dump "${URL}?sslmode=require" \
            --schema=public \
            --schema-only \
            --no-owner \
            --no-privileges \
            --if-exists \
            > docs/architecture/DBschema/schema.sql

      - name: Commit if schema changed
        run: |
          set -e
          if ! git diff --quiet -- docs/architecture/DBschema/schema.sql; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/architecture/DBschema/schema.sql
            git commit -m "chore(schema): update schema [skip ci]"
            git push
          else
            echo "No schema changes"
          fi
