name: Supabase Schema Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2 * * *"   # daily at 02:00 UTC

permissions:
  contents: write

jobs:
  schema-dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

            - name: Install Supabase CLI
        run: |
          set -euo pipefail
          rm -f /tmp/supabase /tmp/supabase.tgz || true
          curl -L -o /tmp/supabase.tgz \
            https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          tar -xzf /tmp/supabase.tgz -C /tmp
          sudo mv -f /tmp/supabase /usr/local/bin/supabase
          sudo chmod +x /usr/local/bin/supabase
          supabase --version

      # Dump the public schema into docs/architecture/DBschema/schema.sql
      - name: Dump public schema
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          mkdir -p docs/architecture/DBschema
          supabase db dump \
            --db-url "$SUPABASE_DB_URL" \
            --schema public \
            > docs/architecture/DBschema/schema.sql

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/architecture/DBschema/schema.sql
          git commit -m "chore(schema): update schema [skip ci]" || echo "No changes to commit"
          git push
